name: CI Pipeline for MyTradingTracking

on:
  push:
    branches:
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clear pytest cache and artifacts
      run: |
        rm -rf .pytest_cache
        find . -type d -name '__pycache__' -exec rm -rf {} +
        find . -type f -name '*.pyc' -delete

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust as needed

    - name: Install dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Run unit tests
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_PROJECT_ID: ${{ secrets.JIRA_PROJECT_ID }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
        TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
        TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
        TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
        TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_TLS_URL: ${{ secrets.REDIS_TLS_URL }}
        INTEGRATION_TEST_URL: ${{ secrets.INTEGRATION_TEST_URL }}
        ENV: ${{ secrets.ENV }}
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest -v -o log_cli=true --log-level=DEBUG src/tests/unit/models/test_user.py

    - name: Deploy to Heroku
      if: success()
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
        docker build -t registry.heroku.com/my-trading-app-staging/web .
        docker push registry.heroku.com/my-trading-app-staging/web
        heroku container:release web --app my-trading-app-staging

    - name: Run integration tests
      if: success()
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_PROJECT_ID: ${{ secrets.JIRA_PROJECT_ID }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
        TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
        TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
        TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
        TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_TLS_URL: ${{ secrets.REDIS_TLS_URL }}
        INTEGRATION_TEST_URL: ${{ secrets.INTEGRATION_TEST_URL }}
        ENV: ${{ secrets.ENV }}
      run: |
        pytest -v src/tests/integration 